version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies for build/test (if any)"
      - cd backend
      - npm install
  build:
    commands:
      - echo "Prisma generation and build..."
      - npx prisma generate
artifacts:
  files:
    - 'server.js'
    - 'package.json'
    - 'ecosystem.config.cjs'
    - 'prisma.config.ts'
    - 'prisma/**/*'
    - 'scripts/**/*'
    - 'appspec.yml'
  base-directory: backend
